name: Create UPM Branch for version Tags
on: 
  create:
    branches:
      - master
    tags:
      - com.gemserk.tests.project1-[0-9].[0-9].[0-9]*

jobs:
  build:
    name: Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Branch
        if: github.event.ref_type == 'tag'
        run: |
          echo 'Testing creating another tag'
          git branch -d ${{env.UPM_BRANCH_NAME}} &> /dev/null || echo ${{env.UPM_BRANCH_NAME}} branch not found
          git subtree split -P "$PKG_ROOT" -b ${{env.UPM_BRANCH_NAME}}
          git checkout ${{env.UPM_BRANCH_NAME}}
          git tag upm/${{env.TAG_NAME}}
          git push --tags -f -u origin ${{env.UPM_BRANCH_NAME}}
    env:
      PKG_NAME: project1
      PKG_ROOT: project1root
      TAG_NAME: ${{github.event.ref}}
      UPM_BRANCH_NAME: upm-$PKG_NAME